<!doctype html>
<html class="no-js" lang="pt-br" ng-app>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Bootstrappin&#39; Portfolio</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <!-- Place favicon.ico in the root directory -->

  <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/main.css')) ?>

  <script src="js/vendor/modernizr-2.8.3.min.js"></script>

  <!-- Respond.js for IE 8 or less only -->
  <!--[if (lt IE 9) & (!IEMobile)]>
  <script src="js/Respond/dest/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <nav role="navigation" class="navbar navbar-static-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <?php $active = (!isset($this->controllerName))? 'active' : '' ?>
            <li class="<?php echo $active ?>">
              <a href="<?php echo $this->url( array('controller'=>''),'default',true) ?>">
                <span class="icon fa fa-home"></span> Home
              </a>
            </li>
            <?php $active = (isset($this->controllerName) and $this->controllerName=='terminal')? 'active' : '' ?>
            <li class="<?php echo $active ?>">
              <a href="<?php echo $this->url( array('controller'=>'terminal'),'default',true) ?>">
                <span class="icon fa fa-desktop"></span> Terminal
              </a>
            </li>
            <?php $active = (isset($this->controllerName) and $this->controllerName=='criptografia')? 'active' : '' ?>
            <li class="<?php echo $active ?>">
              <a href="#">
                <span class="icon fa fa-shield"></span> Criptografia
              </a>
            </li>
            <li>
              <a href="#">
                <span class="icon fa fa-envelope"></span> Contact
              </a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </header>

  <main role="main">
    <?php echo $this->layout()->content ?>
  </main>

  <script src="js/vendor/jquery-1.12.0.min.js"></script>
  <script src="js/terminal.js"></script>
  <script src="js/plugins.js"></script>
  <script src="js/main.js"></script>

</body>
</html>
